// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnrbsjFH4FiajDMHmXWVJtTA3IITQFSiY',
    appId: '1:38594372187:web:1ae2b1d08d9d2f5168157e',
    messagingSenderId: '38594372187',
    projectId: 'doame-21717',
    authDomain: 'doame-21717.firebaseapp.com',
    databaseURL: 'https://doame-21717-default-rtdb.firebaseio.com',
    storageBucket: 'doame-21717.firebasestorage.app',
    measurementId: 'G-SEWKENWXJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoA7a-GEdDv4xpOiWUmAgGNyIctAiLSMM',
    appId: '1:38594372187:android:e6c72b2584b6868c68157e',
    messagingSenderId: '38594372187',
    projectId: 'doame-21717',
    databaseURL: 'https://doame-21717-default-rtdb.firebaseio.com',
    storageBucket: 'doame-21717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJbFkH-IAkkdfqB-H2RuqBwuxcWWvXXmY',
    appId: '1:38594372187:ios:460c5af44999174068157e',
    messagingSenderId: '38594372187',
    projectId: 'doame-21717',
    databaseURL: 'https://doame-21717-default-rtdb.firebaseio.com',
    storageBucket: 'doame-21717.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJbFkH-IAkkdfqB-H2RuqBwuxcWWvXXmY',
    appId: '1:38594372187:ios:460c5af44999174068157e',
    messagingSenderId: '38594372187',
    projectId: 'doame-21717',
    databaseURL: 'https://doame-21717-default-rtdb.firebaseio.com',
    storageBucket: 'doame-21717.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnrbsjFH4FiajDMHmXWVJtTA3IITQFSiY',
    appId: '1:38594372187:web:3c106994a7ee62a868157e',
    messagingSenderId: '38594372187',
    projectId: 'doame-21717',
    authDomain: 'doame-21717.firebaseapp.com',
    databaseURL: 'https://doame-21717-default-rtdb.firebaseio.com',
    storageBucket: 'doame-21717.firebasestorage.app',
    measurementId: 'G-RZ2Z5BNDZ9',
  );
}
